version: '3'

services:
  isis3-cassini:
    build: .
    image: seignovert/isis3-cassini
    container_name: isis3-cassini
    hostname: isis3-cassini
    volumes:
      - $PDS_DATA:/usgs/pds
      - $ISIS3DATA/cassini:/usgs/data/cassini
    stdin_open: true
    tty: true